FROM nginx:alpine-slim

RUN apk add --no-cache bash

COPY nginx.conf.template /etc/nginx/templates/default.conf.template

EXPOSE 80 443

CMD ["/bin/bash", "-c", "envsubst '${DOMAIN}' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
